export const weatherGreetings = {
  rainy: [
    "Puddles splashing at {temp}! ☔️",
    "Perfect puddle weather at {temp}! 💦",
    "Rain tapping away at {temp}! 🌧",
    "Raindrops dancing at {temp}! 🌧",
    "Cozy rain falling at {temp}! ☔️",
    "Pitter patter of rain at {temp}! 🌧",
    "Rain's melody at {temp}! 💦",
    "Puddle paradise at {temp}! 💦",
    "Refreshing showers at {temp}! ☔️",
    "Magical raindrops at {temp}! ✨",
    "Misty drizzle at {temp}! 🌧",
    "Rainbows forming at {temp}! 🌈",
    "Steady rainfall at {temp}! 🌧",
    "Garden-soaking rain at {temp}! 🌱",
    "Gentle rain at {temp}! ☔️",
    "Rain pattering at {temp}! 💦",
    "Showers and mist at {temp}! 🌧",
  ],
  snowy: [
    "Snowflakes falling at {temp}! ❄️",
    "Winter wonderland at {temp}! ⛄️",
    "Snow blanketing everything at {temp}! ❄️",
    "Fresh powder at {temp}! 🌨",
    "Sparkling snowfall at {temp}! ✨",
    "Gentle snowflakes at {temp}! ❄️",
    "Snow-covered landscape at {temp}! ⛄️",
    "Crisp and snowy at {temp}! 🌨",
    "Snow drifting down at {temp}! 🌨",
    "Magical snowfall at {temp}! ❄️",
    "Everything white at {temp}! ❄️",
    "Peaceful snowfall at {temp}! 🌨",
    "Snow globe scene at {temp}! ✨",
    "Fluffy snowflakes at {temp}! ❄️",
    "Winter's blanket at {temp}! 🌨",
    "Pristine snowfall at {temp}! ⛄️",
  ],
  stormy: [
    "Thunder rolling at {temp}! ⚡️",
    "Lightning show at {temp}! 🌩",
    "Storm clouds gathering at {temp}! ⚡️",
    "Nature's concert at {temp}! 🌩",
    "Dramatic skies at {temp}! ⛈",
    "Thunder booming at {temp}! ⚡️",
    "Wild weather at {temp}! 🌩",
    "Storm brewing at {temp}! ☔️",
    "Lightning flashing at {temp}! ⚡️",
    "Turbulent skies at {temp}! 🌩",
    "Storm intensity at {temp}! ⛈",
    "Electric atmosphere at {temp}! ⚡️",
    "Thunderous display at {temp}! 🌩",
    "Stormy conditions at {temp}! ⛈",
    "Weather's fury at {temp}! ⚡️",
    "Storm passing through at {temp}! 🌩",
  ],
  windy: [
    "Winds whirling at {temp}! 🌪",
    "Breezy conditions at {temp}! 🌬",
    "Leaves dancing at {temp}! 🍂",
    "Gusty weather at {temp}! 💨",
    "Wind waves at {temp}! 🌬",
    "Blustery conditions at {temp}! 💨",
    "Wind whistling at {temp}! 🌪",
    "Perfect breeze at {temp}! 🌬",
    "Wind swirling at {temp}! 💨",
    "Clouds racing at {temp}! 🌬",
    "Refreshing winds at {temp}! 🌪",
    "Steady breeze at {temp}! 💨",
    "Wind patterns at {temp}! 🌬",
    "Fresh gusts at {temp}! 💨",
    "Windswept scene at {temp}! 🌪",
    "Brisk winds at {temp}! 🌬",
  ],
  cold: [
    "Frosty morning at {temp}! ❄️",
    "Chilly conditions at {temp}! 🧊",
    "Crisp air at {temp}! ❄️",
    "Winter's chill at {temp}! 🧊",
    "Frosty atmosphere at {temp}! ❄️",
    "Cold snap at {temp}! 🧊",
    "Icy breeze at {temp}! ❄️",
    "Winter's breath at {temp}! 🧊",
    "Frigid air at {temp}! ❄️",
    "Cold front at {temp}! 🧊",
    "Brisk morning at {temp}! ❄️",
    "Winter's touch at {temp}! 🧊",
    "Cool conditions at {temp}! ❄️",
    "Chilly breeze at {temp}! 🧊",
    "Cold spell at {temp}! ❄️",
    "Wintry air at {temp}! 🧊",
  ],
  hot: [
    "Sizzling heat at {temp}! 🌞",
    "Summer's peak at {temp}! 🌡️",
    "Heat wave at {temp}! 🌞",
    "Scorching day at {temp}! 🌡️",
    "Summer intensity at {temp}! 🌞",
    "Blazing sun at {temp}! 🌡️",
    "Hot and bright at {temp}! 🌞",
    "Tropical warmth at {temp}! 🌡️",
    "Summer sizzle at {temp}! 🌞",
    "Heat rising at {temp}! 🌡️",
    "Warm breeze at {temp}! 🌞",
    "Summer weather at {temp}! 🌡️",
    "Sunny and hot at {temp}! 🌞",
    "Balmy conditions at {temp}! 🌡️",
    "Heat settling in at {temp}! 🌞",
    "Warm front at {temp}! 🌡️",
  ],
  clear: [
    "Crystal clear at {temp}! 🌞",
    "Pristine skies at {temp}! ☀️",
    "Blue horizons at {temp}! 🌤",
    "Sunshine sparkling at {temp}! ✨",
    "Clear conditions at {temp}! 🌤",
    "Bright skies at {temp}! 🌟",
    "Sun shining at {temp}! ☀️",
    "Perfect clarity at {temp}! 🌞",
    "Clear blue at {temp}! 🌤",
    "Radiant sunshine at {temp}! ✨",
    "Cloudless skies at {temp}! 🌟",
    "Clear day at {temp}! ☀️",
    "Sun's brilliance at {temp}! 🌞",
    "Perfect visibility at {temp}! ✨",
    "Clear horizon at {temp}! 🌤",
    "Bright sunshine at {temp}! ☀️",
  ],
  neutral: [
    "Mild conditions at {temp}! 🌥",
    "Gentle weather at {temp}! 🌤",
    "Pleasant atmosphere at {temp}! ✨",
    "Calm conditions at {temp}! 🌥",
    "Moderate weather at {temp}! 🌤",
    "Stable conditions at {temp}! ✨",
    "Balanced weather at {temp}! 🌥",
    "Even temperature at {temp}! 🌤",
    "Steady conditions at {temp}! ✨",
    "Temperate day at {temp}! 🌥",
    "Mild atmosphere at {temp}! 🌤",
    "Pleasant conditions at {temp}! ✨",
    "Comfortable weather at {temp}! 🌥",
    "Settled conditions at {temp}! 🌤",
    "Peaceful weather at {temp}! ✨",
    "Tranquil atmosphere at {temp}! 🌥",
  ],
} as const;
