export const weatherGreetings = {
  morning: {
    rainy: [
      "Good morning! Rainy start at {temp}! ☔️",
      "Morning showers at {temp}! 💦",
      "Wet morning at {temp}! 🌧",
      "Rainy dawn at {temp}! ☔️",
      "Morning drizzle at {temp}! 🌧",
      "Wet start to the day at {temp}! 💦",
      "Rainy morning vibes at {temp}! 🌧",
      "Morning rain at {temp}! ☔️",
    ],
    snowy: [
      "Good morning! Snowy start at {temp}! ❄️",
      "Morning snowfall at {temp}! 🌨",
      "Frosty morning at {temp}! ❄️",
      "Snowy dawn at {temp}! ⛄️",
      "Winter morning at {temp}! ❄️",
      "Crisp snowy morning at {temp}! 🌨",
      "Morning winter wonderland at {temp}! ⛄️",
      "Fresh snow this morning at {temp}! ❄️",
    ],
    stormy: [
      "Good morning! Stormy start at {temp}! ⚡️",
      "Morning thunder at {temp}! 🌩",
      "Stormy dawn at {temp}! ⚡️",
      "Morning lightning at {temp}! 🌩",
      "Wild morning weather at {temp}! ⛈",
      "Stormy morning at {temp}! ⚡️",
      "Morning weather drama at {temp}! 🌩",
      "Thunderous morning at {temp}! ⚡️",
    ],
    windy: [
      "Good morning! Breezy start at {temp}! 🌬",
      "Morning winds at {temp}! 💨",
      "Windy dawn at {temp}! 🌪",
      "Morning breeze at {temp}! 🌬",
      "Fresh morning winds at {temp}! 💨",
      "Brisk morning at {temp}! 🌬",
      "Morning wind patterns at {temp}! 💨",
      "Windy morning at {temp}! 🌪",
    ],
    cold: [
      "Good morning! Chilly start at {temp}! ❄️",
      "Cold morning at {temp}! 🧊",
      "Frosty dawn at {temp}! ❄️",
      "Morning chill at {temp}! 🧊",
      "Crisp morning at {temp}! ❄️",
      "Cold start to the day at {temp}! 🧊",
      "Morning frost at {temp}! ❄️",
      "Chilly morning vibes at {temp}! 🧊",
    ],
    hot: [
      "Good morning! Warm start at {temp}! 🌞",
      "Morning heat at {temp}! 🌡️",
      "Hot dawn at {temp}! 🌞",
      "Morning warmth at {temp}! 🌡️",
      "Warm morning at {temp}! 🌞",
      "Morning sunshine at {temp}! 🌡️",
      "Hot start to the day at {temp}! 🌞",
      "Morning heat wave at {temp}! 🌡️",
    ],
    clear: [
      "Good morning! Clear start at {temp}! 🌞",
      "Morning sunshine at {temp}! ☀️",
      "Clear dawn at {temp}! 🌤",
      "Morning clarity at {temp}! ✨",
      "Bright morning at {temp}! 🌟",
      "Morning blue skies at {temp}! ☀️",
      "Clear morning at {temp}! 🌤",
      "Morning radiance at {temp}! ✨",
    ],
    neutral: [
      "Good morning! Mild start at {temp}! 🌥",
      "Morning calm at {temp}! 🌤",
      "Gentle morning at {temp}! ✨",
      "Morning peace at {temp}! 🌥",
      "Pleasant morning at {temp}! 🌤",
      "Morning tranquility at {temp}! ✨",
      "Calm morning at {temp}! 🌥",
      "Morning serenity at {temp}! 🌤",
    ],
  },
  afternoon: {
    rainy: [
      "Afternoon rain at {temp}! ☔️",
      "Wet afternoon at {temp}! 💦",
      "Rainy afternoon vibes at {temp}! 🌧",
      "Afternoon showers at {temp}! ☔️",
      "Rainy midday at {temp}! 💦",
      "Afternoon drizzle at {temp}! 🌧",
      "Wet afternoon at {temp}! ☔️",
      "Rainy afternoon at {temp}! 💦",
    ],
    snowy: [
      "Afternoon snow at {temp}! ❄️",
      "Snowy afternoon at {temp}! 🌨",
      "Afternoon winter at {temp}! ❄️",
      "Snowy midday at {temp}! ⛄️",
      "Afternoon snowfall at {temp}! ❄️",
      "Winter afternoon at {temp}! 🌨",
      "Snowy afternoon vibes at {temp}! ⛄️",
      "Afternoon frost at {temp}! ❄️",
    ],
    stormy: [
      "Afternoon storm at {temp}! ⚡️",
      "Stormy afternoon at {temp}! 🌩",
      "Afternoon thunder at {temp}! ⚡️",
      "Stormy midday at {temp}! 🌩",
      "Afternoon lightning at {temp}! ⚡️",
      "Wild afternoon weather at {temp}! ⛈",
      "Stormy afternoon vibes at {temp}! 🌩",
      "Afternoon weather drama at {temp}! ⚡️",
    ],
    windy: [
      "Afternoon breeze at {temp}! 🌬",
      "Windy afternoon at {temp}! 💨",
      "Afternoon winds at {temp}! 🌪",
      "Breezy midday at {temp}! 🌬",
      "Afternoon gusts at {temp}! 💨",
      "Windy afternoon vibes at {temp}! 🌬",
      "Afternoon wind patterns at {temp}! 💨",
      "Brisk afternoon at {temp}! 🌪",
    ],
    cold: [
      "Cold afternoon at {temp}! ❄️",
      "Chilly afternoon at {temp}! 🧊",
      "Afternoon chill at {temp}! ❄️",
      "Cold midday at {temp}! 🧊",
      "Afternoon frost at {temp}! ❄️",
      "Chilly afternoon vibes at {temp}! 🧊",
      "Afternoon cold snap at {temp}! ❄️",
      "Cold afternoon at {temp}! 🧊",
    ],
    hot: [
      "Hot afternoon at {temp}! 🌞",
      "Afternoon heat at {temp}! 🌡️",
      "Scorching afternoon at {temp}! 🌞",
      "Hot midday at {temp}! 🌡️",
      "Afternoon warmth at {temp}! 🌞",
      "Hot afternoon vibes at {temp}! 🌡️",
      "Afternoon heat wave at {temp}! 🌞",
      "Sizzling afternoon at {temp}! 🌡️",
    ],
    clear: [
      "Clear afternoon at {temp}! 🌞",
      "Afternoon sunshine at {temp}! ☀️",
      "Clear midday at {temp}! 🌤",
      "Afternoon clarity at {temp}! ✨",
      "Bright afternoon at {temp}! 🌟",
      "Afternoon blue skies at {temp}! ☀️",
      "Clear afternoon vibes at {temp}! 🌤",
      "Afternoon radiance at {temp}! ✨",
    ],
    neutral: [
      "Mild afternoon at {temp}! 🌥",
      "Afternoon calm at {temp}! 🌤",
      "Gentle afternoon at {temp}! ✨",
      "Pleasant afternoon at {temp}! 🌥",
      "Afternoon peace at {temp}! 🌤",
      "Calm afternoon at {temp}! ✨",
      "Afternoon tranquility at {temp}! 🌥",
      "Mild afternoon vibes at {temp}! 🌤",
    ],
  },
  evening: {
    rainy: [
      "Evening rain at {temp}! ☔️",
      "Rainy evening at {temp}! 💦",
      "Evening showers at {temp}! 🌧",
      "Wet evening at {temp}! ☔️",
      "Rainy sunset at {temp}! 💦",
      "Evening drizzle at {temp}! 🌧",
      "Rainy evening vibes at {temp}! ☔️",
      "Evening rainfall at {temp}! 💦",
    ],
    snowy: [
      "Evening snow at {temp}! ❄️",
      "Snowy evening at {temp}! 🌨",
      "Evening snowfall at {temp}! ❄️",
      "Snowy sunset at {temp}! ⛄️",
      "Evening winter at {temp}! ❄️",
      "Snowy evening vibes at {temp}! 🌨",
      "Evening frost at {temp}! ❄️",
      "Winter evening at {temp}! ⛄️",
    ],
    stormy: [
      "Evening storm at {temp}! ⚡️",
      "Stormy evening at {temp}! 🌩",
      "Evening thunder at {temp}! ⚡️",
      "Stormy sunset at {temp}! 🌩",
      "Evening lightning at {temp}! ⚡️",
      "Stormy evening vibes at {temp}! ⛈",
      "Evening weather drama at {temp}! 🌩",
      "Thunderous evening at {temp}! ⚡️",
    ],
    windy: [
      "Evening breeze at {temp}! 🌬",
      "Windy evening at {temp}! 💨",
      "Evening winds at {temp}! 🌪",
      "Breezy sunset at {temp}! 🌬",
      "Evening gusts at {temp}! 💨",
      "Windy evening vibes at {temp}! 🌬",
      "Evening wind patterns at {temp}! 💨",
      "Brisk evening at {temp}! 🌪",
    ],
    cold: [
      "Cold evening at {temp}! ❄️",
      "Chilly evening at {temp}! 🧊",
      "Evening chill at {temp}! ❄️",
      "Cold sunset at {temp}! 🧊",
      "Evening frost at {temp}! ❄️",
      "Chilly evening vibes at {temp}! 🧊",
      "Evening cold snap at {temp}! ❄️",
      "Cold evening at {temp}! 🧊",
    ],
    hot: [
      "Warm evening at {temp}! 🌞",
      "Evening heat at {temp}! 🌡️",
      "Hot sunset at {temp}! 🌞",
      "Evening warmth at {temp}! 🌡️",
      "Warm evening vibes at {temp}! 🌞",
      "Evening heat at {temp}! 🌡️",
      "Balmy evening at {temp}! 🌞",
      "Warm evening at {temp}! 🌡️",
    ],
    clear: [
      "Clear evening at {temp}! 🌞",
      "Evening sunshine at {temp}! ☀️",
      "Clear sunset at {temp}! 🌤",
      "Evening clarity at {temp}! ✨",
      "Bright evening at {temp}! 🌟",
      "Evening blue skies at {temp}! ☀️",
      "Clear evening vibes at {temp}! 🌤",
      "Evening radiance at {temp}! ✨",
    ],
    neutral: [
      "Mild evening at {temp}! 🌥",
      "Evening calm at {temp}! 🌤",
      "Gentle evening at {temp}! ✨",
      "Pleasant evening at {temp}! 🌥",
      "Evening peace at {temp}! 🌤",
      "Calm evening at {temp}! ✨",
      "Evening tranquility at {temp}! 🌥",
      "Mild evening vibes at {temp}! 🌤",
    ],
  },
  night: {
    rainy: [
      "Night rain at {temp}! ☔️",
      "Rainy night at {temp}! 💦",
      "Night showers at {temp}! 🌧",
      "Wet night at {temp}! ☔️",
      "Rainy darkness at {temp}! 💦",
      "Night drizzle at {temp}! 🌧",
      "Rainy night vibes at {temp}! ☔️",
      "Night rainfall at {temp}! 💦",
    ],
    snowy: [
      "Night snow at {temp}! ❄️",
      "Snowy night at {temp}! 🌨",
      "Night snowfall at {temp}! ❄️",
      "Snowy darkness at {temp}! ⛄️",
      "Night winter at {temp}! ❄️",
      "Snowy night vibes at {temp}! 🌨",
      "Night frost at {temp}! ❄️",
      "Winter night at {temp}! ⛄️",
    ],
    stormy: [
      "Night storm at {temp}! ⚡️",
      "Stormy night at {temp}! 🌩",
      "Night thunder at {temp}! ⚡️",
      "Stormy darkness at {temp}! 🌩",
      "Night lightning at {temp}! ⚡️",
      "Stormy night vibes at {temp}! ⛈",
      "Night weather drama at {temp}! 🌩",
      "Thunderous night at {temp}! ⚡️",
    ],
    windy: [
      "Night breeze at {temp}! 🌬",
      "Windy night at {temp}! 💨",
      "Night winds at {temp}! 🌪",
      "Breezy darkness at {temp}! 🌬",
      "Night gusts at {temp}! 💨",
      "Windy night vibes at {temp}! 🌬",
      "Night wind patterns at {temp}! 💨",
      "Brisk night at {temp}! 🌪",
    ],
    cold: [
      "Cold night at {temp}! ❄️",
      "Chilly night at {temp}! 🧊",
      "Night chill at {temp}! ❄️",
      "Cold darkness at {temp}! 🧊",
      "Night frost at {temp}! ❄️",
      "Chilly night vibes at {temp}! 🧊",
      "Night cold snap at {temp}! ❄️",
      "Cold night at {temp}! 🧊",
    ],
    hot: [
      "Warm night at {temp}! 🌙",
      "Night heat at {temp}! 🌡️",
      "Hot night at {temp}! 🌙",
      "Night warmth at {temp}! 🌡️",
      "Warm night vibes at {temp}! 🌙",
      "Night heat at {temp}! 🌡️",
      "Balmy night at {temp}! 🌙",
      "Warm night at {temp}! 🌡️",
    ],
    clear: [
      "Clear night at {temp}! 🌙",
      "Night stars at {temp}! ⭐",
      "Clear darkness at {temp}! 🌌",
      "Night clarity at {temp}! ✨",
      "Starry night at {temp}! ⭐",
      "Night sky at {temp}! 🌙",
      "Clear night vibes at {temp}! 🌌",
      "Night radiance at {temp}! ✨",
    ],
    neutral: [
      "Mild night at {temp}! 🌙",
      "Night calm at {temp}! 🌌",
      "Gentle night at {temp}! ✨",
      "Pleasant night at {temp}! 🌙",
      "Night peace at {temp}! 🌌",
      "Calm night at {temp}! ✨",
      "Night tranquility at {temp}! 🌙",
      "Mild night vibes at {temp}! 🌌",
    ],
  },
  // Legacy format for backward compatibility
  rainy: [
    "Puddles splashing at {temp}! ☔️",
    "Perfect puddle weather at {temp}! 💦",
    "Rain tapping away at {temp}! 🌧",
    "Raindrops dancing at {temp}! 🌧",
    "Cozy rain falling at {temp}! ☔️",
    "Pitter patter of rain at {temp}! 🌧",
    "Rain's melody at {temp}! 💦",
    "Puddle paradise at {temp}! 💦",
    "Refreshing showers at {temp}! ☔️",
    "Magical raindrops at {temp}! ✨",
    "Misty drizzle at {temp}! 🌧",
    "Rainbows forming at {temp}! 🌈",
    "Steady rainfall at {temp}! 🌧",
    "Garden-soaking rain at {temp}! 🌱",
    "Gentle rain at {temp}! ☔️",
    "Rain pattering at {temp}! 💦",
    "Showers and mist at {temp}! 🌧",
  ],
  snowy: [
    "Snowflakes falling at {temp}! ❄️",
    "Winter wonderland at {temp}! ⛄️",
    "Snow blanketing everything at {temp}! ❄️",
    "Fresh powder at {temp}! 🌨",
    "Sparkling snowfall at {temp}! ✨",
    "Gentle snowflakes at {temp}! ❄️",
    "Snow-covered landscape at {temp}! ⛄️",
    "Crisp and snowy at {temp}! 🌨",
    "Snow drifting down at {temp}! 🌨",
    "Magical snowfall at {temp}! ❄️",
    "Everything white at {temp}! ❄️",
    "Peaceful snowfall at {temp}! 🌨",
    "Snow globe scene at {temp}! ✨",
    "Fluffy snowflakes at {temp}! ❄️",
    "Winter's blanket at {temp}! 🌨",
    "Pristine snowfall at {temp}! ⛄️",
  ],
  stormy: [
    "Thunder rolling at {temp}! ⚡️",
    "Lightning show at {temp}! 🌩",
    "Storm clouds gathering at {temp}! ⚡️",
    "Nature's concert at {temp}! 🌩",
    "Dramatic skies at {temp}! ⛈",
    "Thunder booming at {temp}! ⚡️",
    "Wild weather at {temp}! 🌩",
    "Storm brewing at {temp}! ☔️",
    "Lightning flashing at {temp}! ⚡️",
    "Turbulent skies at {temp}! 🌩",
    "Storm intensity at {temp}! ⛈",
    "Electric atmosphere at {temp}! ⚡️",
    "Thunderous display at {temp}! 🌩",
    "Stormy conditions at {temp}! ⛈",
    "Weather's fury at {temp}! ⚡️",
    "Storm passing through at {temp}! 🌩",
  ],
  windy: [
    "Winds whirling at {temp}! 🌪",
    "Breezy conditions at {temp}! 🌬",
    "Leaves dancing at {temp}! 🍂",
    "Gusty weather at {temp}! 💨",
    "Wind waves at {temp}! 🌬",
    "Blustery conditions at {temp}! 💨",
    "Wind whistling at {temp}! 🌪",
    "Perfect breeze at {temp}! 🌬",
    "Wind swirling at {temp}! 💨",
    "Clouds racing at {temp}! 🌬",
    "Refreshing winds at {temp}! 🌪",
    "Steady breeze at {temp}! 💨",
    "Wind patterns at {temp}! 🌬",
    "Fresh gusts at {temp}! 💨",
    "Windswept scene at {temp}! 🌪",
    "Brisk winds at {temp}! 🌬",
  ],
  cold: [
    "Frosty morning at {temp}! ❄️",
    "Chilly conditions at {temp}! 🧊",
    "Crisp air at {temp}! ❄️",
    "Winter's chill at {temp}! 🧊",
    "Frosty atmosphere at {temp}! ❄️",
    "Cold snap at {temp}! 🧊",
    "Icy breeze at {temp}! ❄️",
    "Winter's breath at {temp}! 🧊",
    "Frigid air at {temp}! ❄️",
    "Cold front at {temp}! 🧊",
    "Brisk morning at {temp}! ❄️",
    "Winter's touch at {temp}! 🧊",
    "Cool conditions at {temp}! ❄️",
    "Chilly breeze at {temp}! 🧊",
    "Cold spell at {temp}! ❄️",
    "Wintry air at {temp}! 🧊",
  ],
  hot: [
    "Sizzling heat at {temp}! 🌞",
    "Summer's peak at {temp}! 🌡️",
    "Heat wave at {temp}! 🌞",
    "Scorching day at {temp}! 🌡️",
    "Summer intensity at {temp}! 🌞",
    "Blazing sun at {temp}! 🌡️",
    "Hot and bright at {temp}! 🌞",
    "Tropical warmth at {temp}! 🌡️",
    "Summer sizzle at {temp}! 🌞",
    "Heat rising at {temp}! 🌡️",
    "Warm breeze at {temp}! 🌞",
    "Summer weather at {temp}! 🌡️",
    "Sunny and hot at {temp}! 🌞",
    "Balmy conditions at {temp}! 🌡️",
    "Heat settling in at {temp}! 🌞",
    "Warm front at {temp}! 🌡️",
  ],
  clear: [
    "Crystal clear at {temp}! 🌞",
    "Pristine skies at {temp}! ☀️",
    "Blue horizons at {temp}! 🌤",
    "Sunshine sparkling at {temp}! ✨",
    "Clear conditions at {temp}! 🌤",
    "Bright skies at {temp}! 🌟",
    "Sun shining at {temp}! ☀️",
    "Perfect clarity at {temp}! 🌞",
    "Clear blue at {temp}! 🌤",
    "Radiant sunshine at {temp}! ✨",
    "Cloudless skies at {temp}! 🌟",
    "Clear day at {temp}! ☀️",
    "Sun's brilliance at {temp}! 🌞",
    "Perfect visibility at {temp}! ✨",
    "Clear horizon at {temp}! 🌤",
    "Bright sunshine at {temp}! ☀️",
  ],
  neutral: [
    "Mild conditions at {temp}! 🌥",
    "Gentle weather at {temp}! 🌤",
    "Pleasant atmosphere at {temp}! ✨",
    "Calm conditions at {temp}! 🌥",
    "Moderate weather at {temp}! 🌤",
    "Stable conditions at {temp}! ✨",
    "Balanced weather at {temp}! 🌥",
    "Even temperature at {temp}! 🌤",
    "Steady conditions at {temp}! ✨",
    "Temperate day at {temp}! 🌥",
    "Mild atmosphere at {temp}! 🌤",
    "Pleasant conditions at {temp}! ✨",
    "Comfortable weather at {temp}! 🌥",
    "Settled conditions at {temp}! 🌤",
    "Peaceful weather at {temp}! ✨",
    "Tranquil atmosphere at {temp}! 🌥",
  ],
} as const;
